# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model3501_pb2 as model3501__pb2


class GreetingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHi = channel.unary_unary(
                '/hi_hello.GreetingService/SayHi',
                request_serializer=model3501__pb2.HiRequest.SerializeToString,
                response_deserializer=model3501__pb2.HiResponse.FromString,
                )
        self.SayHello = channel.unary_unary(
                '/hi_hello.GreetingService/SayHello',
                request_serializer=model3501__pb2.HelloRequest.SerializeToString,
                response_deserializer=model3501__pb2.HelloResponse.FromString,
                )
        self.FindUsbDevice = channel.unary_unary(
                '/hi_hello.GreetingService/FindUsbDevice',
                request_serializer=model3501__pb2.FindUsbDeviceRequest.SerializeToString,
                response_deserializer=model3501__pb2.FindUsbDeviceResponse.FromString,
                )
        self.SetDeviceSpeed = channel.unary_unary(
                '/hi_hello.GreetingService/SetDeviceSpeed',
                request_serializer=model3501__pb2.SpeedRequest.SerializeToString,
                response_deserializer=model3501__pb2.SpeedResponse.FromString,
                )
        self.SendData = channel.unary_unary(
                '/hi_hello.GreetingService/SendData',
                request_serializer=model3501__pb2.DataRequest.SerializeToString,
                response_deserializer=model3501__pb2.DataResponse.FromString,
                )


class GreetingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUsbDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDeviceSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreetingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHi': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHi,
                    request_deserializer=model3501__pb2.HiRequest.FromString,
                    response_serializer=model3501__pb2.HiResponse.SerializeToString,
            ),
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=model3501__pb2.HelloRequest.FromString,
                    response_serializer=model3501__pb2.HelloResponse.SerializeToString,
            ),
            'FindUsbDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUsbDevice,
                    request_deserializer=model3501__pb2.FindUsbDeviceRequest.FromString,
                    response_serializer=model3501__pb2.FindUsbDeviceResponse.SerializeToString,
            ),
            'SetDeviceSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDeviceSpeed,
                    request_deserializer=model3501__pb2.SpeedRequest.FromString,
                    response_serializer=model3501__pb2.SpeedResponse.SerializeToString,
            ),
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=model3501__pb2.DataRequest.FromString,
                    response_serializer=model3501__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hi_hello.GreetingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreetingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hi_hello.GreetingService/SayHi',
            model3501__pb2.HiRequest.SerializeToString,
            model3501__pb2.HiResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hi_hello.GreetingService/SayHello',
            model3501__pb2.HelloRequest.SerializeToString,
            model3501__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindUsbDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hi_hello.GreetingService/FindUsbDevice',
            model3501__pb2.FindUsbDeviceRequest.SerializeToString,
            model3501__pb2.FindUsbDeviceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDeviceSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hi_hello.GreetingService/SetDeviceSpeed',
            model3501__pb2.SpeedRequest.SerializeToString,
            model3501__pb2.SpeedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hi_hello.GreetingService/SendData',
            model3501__pb2.DataRequest.SerializeToString,
            model3501__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
